// 👉 Create Element Using JavaScript

// 1. createElement: Creates an instance of the element for the specified tag.

const divEle = document.createElement("div");

// 2. className: Can set the class using JavaScript.

divEle.className = "js_div_element";

// 3. setAttribute: Used to set an attribute to HTML elements.

divEle.setAttribute("title", "js generated title");

// 3. CreateTextNode: Creates a text string from the specified value.

const eleText = document.createTextNode(
  "This element generated by JavaScript."
);

// 4. AppendChild: This method appends a node (element) as the last child of an element.

divEle.appendChild(eleText);

// Finally Append to body
document.body.appendChild(divEle);

// Styling to Div
divEle.style.background = "royalBlue";
divEle.style.color = "white";
divEle.style.border = "2px solid yellow";
divEle.style.padding = "10px";
